# Generated by Django 5.1 on 2024-08-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='about_us/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name': 'Настройки главной страницы', 'verbose_name_plural': 'Настройки главной страницы'},
        ),
        migrations.AlterField(
            model_name='index',
            name='banner',
            field=models.ImageField(upload_to='image/', verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='index',
            name='description',
            field=models.TextField(verbose_name='Описание сайта'),
        ),
        migrations.AlterField(
            model_name='index',
            name='facebook',
            field=models.URLField(verbose_name='Укажите ссылку на Facebook'),
        ),
        migrations.AlterField(
            model_name='index',
            name='github',
            field=models.URLField(verbose_name='Укажите ссылку на GitHub'),
        ),
        migrations.AlterField(
            model_name='index',
            name='gmail',
            field=models.URLField(verbose_name='Укажите ссылку на почту'),
        ),
        migrations.AlterField(
            model_name='index',
            name='twitter',
            field=models.URLField(verbose_name='Укажите ссылку на Twitter'),
        ),
    ]
